query GetAllCountries {
	countries {
		code
		name
		currency
	}
}

query SearchCountriesWithCurrency($filter: CountryFilterInput) {
	countries(filter: $filter) {
		code
		name
		currency
	}
}

query SearchCountries($filter: CountryFilterInput) {
	countries(filter: $filter) {
		code
		name
	}
}
